name: 💬 Question
description: Ask a question about the project.
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please make sure that you have read through our documentation and existing [issues](https://github.com/repolens-ai/sdk/issues) to see if it has already been answered. If it has, please add your reaction to the existing issue instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
